# Generated by Django 4.1.6 on 2023-02-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=128)),
                ('last_name', models.CharField(db_column='last_name', max_length=128)),
                ('personal_email', models.EmailField(db_column='personal_email', max_length=256)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Polygender', 'P'), ('Genderfluid', 'G'), ('Agender', 'A'), ('Bigender', 'B')], db_column='gender', max_length=11)),
                ('birth_date', models.DateField(db_column='birth_date')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
