# Generated by Django 4.1.6 on 2023-02-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_column='company_name', max_length=256)),
                ('country', models.CharField(db_column='country', max_length=128)),
                ('city', models.CharField(db_column='city', max_length=128)),
                ('address', models.CharField(db_column='address', max_length=128)),
                ('phone_num', models.CharField(db_column='phone_num', max_length=128)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(db_column='job_title', max_length=256)),
                ('is_current_job', models.BooleanField(db_column='is_current_job')),
                ('employee_email', models.EmailField(db_column='employee_email', max_length=254, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_app.company')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_app.person')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(through='employees_app.Employee', to='employees_app.person'),
        ),
    ]
